version: '3.8'

services:
  webserver:
    build:
      context: .
    ports:
      - "1337:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - ./config/supervisord.conf:/etc/supervisord.conf
      - ./challenge:/www
      - ./flag:/flag
    restart: always