version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - ./config/supervisord.conf:/etc/supervisord.conf
    environment:
      PYTHONDONTWRITEBYTECODE: "1"